spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${MYSQLPORT:5000}


razorpay:
  api:
    key: ${RAZORPAY_KEY:your_razorpay_key}
    secret: ${RAZORPAY_SECRET:your_razorpay_secret}

stripe:
  api:
    key: ${STRIPE_KEY:your_stripe_key}

app:
  frontend:
    reset-url: ${FRONTEND_RESET_URL:http://localhost:5173/auth/reset-password?token=}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
