spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:railway}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

razorpay:
  api:
    key: ${RAZORPAY_KEY:dummy_key}
    secret: ${RAZORPAY_SECRET:dummy_secret}

stripe:
  api:
    key: ${STRIPE_KEY:dummy_key}

app:
  frontend:
    reset-url: ${FRONTEND_RESET_URL:http://localhost:5173/auth/reset-password?token=}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG           # SQL queries
    org.hibernate.type: WARN           # suppress type registration
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  

            
            

