spring:
  application:
    name: pos-system

  datasource:
    # Use host.docker.internal to let container access MySQL on host
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:${DB_PORT:3301}/${DB_NAME:pos}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your_email}
    password: ${MAIL_PASSWORD:your_gmail_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true

server:
  port: ${PORT:5000}

razorpay:
  api:
    key: ${RAZORPAY_KEY:your_razorpay_key}
    secret: ${RAZORPAY_SECRET:your_razorpay_secret}

stripe:
  api:
    key: ${STRIPE_KEY:your_stripe_key}

app:
  frontend:
    reset-url: ${FRONTEND_RESET_URL:http://localhost:5173/auth/reset-password?token=}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
